### PR TITLE
Fix Problems with glmGamPoi Integration

### PR DESCRIPTION
**Pull request by const-ae**
Hi Mike,

I have now exported `loc_median_fit()` from glmGamPoi and call it with the `::` notation.
I have also fixed an issue, because I renamed one of the returned objects from `estimate` to `estimates` in glmGamPoi (sorry about that).

The R CMD check should now run without problems.

In https://github.com/mikelove/DESeq2/commit/d3c1075a84800a64284585c790e9ed1e04d4abac, you added a switch for the `minmu` argument of the `DESeq()` function. Does it make sense to add a similar switch to `nbinomLRT()` and `estimateDispersionsGeneEst()`?

Best,
Constantin

### CODE REVIEW

**Comment by mikelove** [comment]
Excellent — I’ll pull this later today. 

I’ll add additional switches for sub-functions today.

I found the “estimates” also and fixed :-)

**Comment by const-ae** [comment]
> Excellent — I’ll pull this later today.

Great, thank you :)

> I’ll add additional switches for sub-functions today.

Okay, nice. The only function, where I am not quite sure how this would work, is the `results()` function. But I also don't quite understand when `results()` actually refits the coefficients.

**Comment by mikelove** [comment]
I can add this in as well, perhaps with a `attr` which is how I look up the `test` status and other attributes.

`results()` runs one iteration of the IRLS in some cases in order to generate the covariance matrix to perform a contrast that cannot be created directly from existing beta and SE. While we store beta and SE in `mcols(dds)` which are `n x p`, it would be cumbersome to store the `n x p x p` covariances.

**Comment by mikelove** [comment]
Now that I think about it, as we don't implement contrasts for `results()` for LRT, then `minmu` is not used when extracting `results()` following glmGamPoi fits. 

I've pushed through the switch for sub-functions `estimateDispersionsGeneEst`, `estimateDispersions`, `nbinomLRT`.

**Comment by const-ae** [comment]
Okay, great. 

> Now that I think about it, as we don't implement contrasts for results() for LRT, then minmu is not used when extracting results() following glmGamPoi fits.

That makes sense.

> I've pushed through the switch for sub-functions `estimateDispersionsGeneEst`, `estimateDispersions`, `nbinomLRT`.

Great, thank you for taking care of this so quickly :)

**Pull request merged**
