### PR TITLE
Integrate glmGamPoi [WIP]

### PR DESCRIPTION
**Pull request by const-ae**
Hi Mike,

as discussed in our email 2 weeks ago, I have started to work on a switch for DESeq2 to make it call `glmGamPoi`. The work isn't finished, but I thought it would be helpful to get your feedback at this point.

I see multiple options how to integrate glmGamPoi and would like to hear your opinion which one you prefer:

1. Only call glmGamPoi inside `estimateDispersionsGeneEst()`. This is the least invasive option and would correspond to 
c3d0e08 and c224b16 from this PR.  As you can see, I still have to call some private functions from glmGamPoi. To fix this, I will have to adapt the interface of glmGamPoi, I just haven't decided what's the best way to do this is yet.

2. Provide glmGamPoi for all three functions called inside `estimateDispersions()`. This would probably follow along the other 4 commits. However, the `estimateDispersionMAP()` (fbb92e2) is a bit tricky, because glmGamPoi follows the quasi-likelihood idea from edgeR (https://github.com/const-ae/glmGamPoi/commit/3835cacb26d94e74712603c078901e29a9e47d1b#diff-6302ed115c823046b309b180da9bbebeR62) and I am currently doing some adhoc conversion to get the shrunken dispersion estimates. The upside of this part is that `DESeq2` spends most of its time in the `estimateDispersionMAP()` function, which I don't think is necessary and thus the gain in performance would be largest.

3. Add a quasi-likelihood ratio test. Based on (2), it is pretty straight forward to implement a quasi-likelihood ratio test along the lines of [Lund et al. (2012)](https://europepmc.org/article/med/23104842) ([implementation](https://github.com/const-ae/glmGamPoi/blob/feature-shrinkage/R/quasi_gamma_poisson_shrinkage.R#L7) in glmGamPoi). This wouldn't necessarily improve the speed, but it could make the test more reliable and might help for example with the email that Matthew Stephens send to us last year. I did some preliminary experiments last week and had the impression that the QLR test works well for traditional bulk and single cell datasets.

Best, Constantin

### CODE REVIEW

**Comment by mikelove** [comment]
Dear Constantin,

Thanks for your contribution. I would opt for (2) and (3), and just have the switch also dictate a switch from the traditional Wald / LRT that ignore estimation of dispersion to quasi-likelihood, which has been shown throughout a number of evaluations to better control FDR.

Have you considered writing up glmGamPoi as an application note or F1000Research article? This would allow you to explain the methods and implementation changes, and also have a citation for when users switch the underlying engine.

Would it be helpful for me to merge this PR already, and push changes to Bioconductor? I can do some testing later this month on my end as well, maybe adding some unit tests.

**Comment by const-ae** [comment]
> I would opt for (2) and (3), and just have the switch also dictate a switch from the traditional Wald / LRT that ignore estimation of dispersion to quasi-likelihood, which has been shown throughout a number of evaluations to better control FDR.

Great. Yes that sounds like a good way forward.

> Have you considered writing up glmGamPoi as an application note or F1000Research article? 

I thought about writing something up and I agree that it would be probably be a good idea, but I haven't talked to Wolfgang about it yet. I will let you know about what we decide :)

> Would it be helpful for me to merge this PR already, and push changes to Bioconductor? 

No, the PR isn't that ready yet. I will first try to get the checks to pass on my side (e.g. remove calls to private functions) and will let you know when it's ready, so that you can check if it works on your side :)

**Comment by const-ae** [comment]
I think, the PR is now ready for a review. 

There is still one function call to a private function from the glmGamPoi package which generates a Note during the check. 
And secondly, I found that the default value of `minmu = 0.5` has a large impact on the results for single cell data. I usually set it to something very small like  `1e-6`, but I am not sure if you want to change that default in general or if a warning should be generated if many values are at that lower limit.

**Comment by const-ae** [comment]
Ah and I also talked to Wolfgang about writing up what I did with glmGamPoi. He suggested to write an Applications Note for Bioinformatics. That's what I would focus on next: covering a simple benchmark, and some description how one can integrate it into tools with DESeq2 as an example.

**Comment by mikelove** [comment]
This sounds like a great idea. Did you want to show a simple example with single cell? We've been quantifying and exploring the mouse embryo data from Marioni lab and others from 2018. Has some interesting cell clusters you could demonstrate DE on.

https://github.com/MarioniLab/EmbryoTimecourse2018

**Comment by const-ae** [comment]
> Did you want to show a simple example with single cell?

Yes exactly.

> We've been quantifying and exploring the mouse embryo data from Marioni lab and others from 2018.

Thanks for the suggestion. I have so far always just used the `TENxPBMCData::TENxPBMCData("pbmc4k")` dataset, but the Marioni Lab one looks better suited for this task. I will explore it tomorrow :)

**Comment by mikelove** [comment]
I'm reminded to come back and review this code. I'm going to merge the PR and kick some tires in the devel branch now.

Given that `fitType` is now a switch that the user will be indicating , I could change to minmu 1e-6 based on that selection. Previously it was only mentioned as recommended in the vignette for single cell, but the code didn't make this change on behalf of the user.

**Comment by mikelove** [comment]
I've put this in as a switch now:

d3c1075

**Comment by mikelove** [comment]
So do you think you will export `glmGamPoi:::loc_median_fit’?

**Comment by mikelove** [comment]
Another commit, 7666878, puts the new bioRxiv into the refs and will print a message regarding the preprint in the dispersion step (not in GLM just so it won't be redundant). Works?

**Comment by const-ae** [comment]
Hey, thanks for merging.

> Given that fitType is now a switch that the user will be indicating , I could change to minmu 1e-6 based on that selection.
> I've put this in as a switch now

I like that idea, that is a nice way to make it transparent for the user what is happening.

> So do you think you will export `glmGamPoi:::loc_median_fit’?

Yes, I will update glmGamPoi and submit a new PR in the next days, where I clean up the code a bit and make sure all checks pass without WARNINGS or NOTES.

> Another commit, 7666878, puts the new bioRxiv into the refs and will print a message regarding the preprint in the dispersion step (not in GLM just so it won't be redundant). Works?

Yes, looks great. Thank you again so much :)

**Comment by c5creative** [comment]
I was just reading @const-ae's Biorxiv manuscript (https://www.biorxiv.org/content/10.1101/2020.08.13.249623v2.full.pdf) and saw the link to this page, then saw @mikelove "kicking the tires" on the master branch. Thank you both so much! Can't wait to try this out!

**Pull request merged**
